name: Deploy to Google Apps Script

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install clasp
      run: npm install -g @google/clasp

    - name: Create .clasprc.json
  run: |
    echo '${{ secrets.CLASPRC_JSON }}' | jq '.' > ~/.clasprc.json


    - name: Run Unit Tests (optional)
      run: |
        clasp push
        echo "✅ Code pushed. You can run tests manually in GAS Editor if needed."

    - name: Done
      run: echo "🚀 Deployment complete!"